//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLedger
    {
        public int id { get; set; }
        public string customerID { get; set; }
        public string referenceNo { get; set; }
        public System.DateTime date { get; set; }
        public decimal receivable { get; set; }
        public decimal amountPaid { get; set; }
        public short lkCreditStatusID { get; set; }
        public bool isActive { get; set; }
        public string branchID { get; set; }
    
        public virtual CreditStatus CreditStatus { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
