//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Sales = new HashSet<Sale>();
            this.TelephoneFaxes = new HashSet<TelephoneFax>();
            this.CustomerLedgers = new HashSet<CustomerLedger>();
            this.WriteOffs = new HashSet<WriteOff>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string fatherName { get; set; }
        public string companyName { get; set; }
        public string TINNo { get; set; }
        public string VATRegistrationNo { get; set; }
        public Nullable<System.DateTime> VATRegistrationDate { get; set; }
        public bool isActive { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.Guid> addressID { get; set; }
        public string grandfatherName { get; set; }
        public Nullable<decimal> creditLimit { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<TelephoneFax> TelephoneFaxes { get; set; }
        public virtual ICollection<CustomerLedger> CustomerLedgers { get; set; }
        public virtual ICollection<WriteOff> WriteOffs { get; set; }
    }
}
