//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.IssuedItems = new HashSet<IssuedItem>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.ReceivedItems = new HashSet<ReceivedItem>();
            this.ReturnedItems = new HashSet<ReturnedItem>();
            this.SalesDetails = new HashSet<SalesDetail>();
            this.LossAdjustments = new HashSet<LossAdjustment>();
        }
    
        public string itemID { get; set; }
        public int rlkBrandID { get; set; }
        public int rlkCategoryID { get; set; }
        public string origin { get; set; }
        public double unitPrice { get; set; }
        public Nullable<double> reorderLevel { get; set; }
        public Nullable<double> pickFaceQty { get; set; }
        public int rlkUnitID { get; set; }
        public Nullable<double> orderQuantity { get; set; }
        public string description { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> rlkTaxTypeID { get; set; }
        public Nullable<bool> isTaxExempted { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public decimal averageCost { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual TaxType TaxType { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<IssuedItem> IssuedItems { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<ReceivedItem> ReceivedItems { get; set; }
        public virtual ICollection<ReturnedItem> ReturnedItems { get; set; }
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
        public virtual ICollection<LossAdjustment> LossAdjustments { get; set; }
    }
}
