//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequest
    {
        public System.Guid salesID { get; set; }
        public string branchID { get; set; }
        public string referenceNo { get; set; }
        public string itemID { get; set; }
        public string warehouseID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
