//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Roles = new HashSet<Role>();
            this.Forms = new HashSet<Form>();
        }
    
        public int id { get; set; }
        public int rlkMenuTypeID { get; set; }
        public string caption { get; set; }
        public byte[] icon { get; set; }
        public int parent { get; set; }
        public int order { get; set; }
        public bool visible { get; set; }
        public bool disabled { get; set; }
        public bool isActive { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual MenuType MenuType { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Form> Forms { get; set; }
    }
}
