//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivedItem
    {
        public string receiptID { get; set; }
        public System.Guid receiptDetailID { get; set; }
        public string itemID { get; set; }
        public string rlkManufacturerID { get; set; }
        public Nullable<int> noPack { get; set; }
        public Nullable<int> qtyPerPack { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
        public double unitSellingPrice { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Item Item { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
