//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnedItem
    {
        public System.Guid salesReturnID { get; set; }
        public System.Guid returnedDetailID { get; set; }
        public string itemID { get; set; }
        public int quantity { get; set; }
        public double refundedAmount { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SalesReturn SalesReturn { get; set; }
    }
}
