//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLocation
    {
        public SalesLocation()
        {
            this.SalesDetails = new HashSet<SalesDetail>();
        }
    
        public short lkSalesLocationID { get; set; }
        public string name { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
    }
}
