//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        public System.Guid salesID { get; set; }
        public System.Guid salesDetailID { get; set; }
        public string itemID { get; set; }
        public short salesFrom { get; set; }
        public long quantity { get; set; }
        public Nullable<double> discount { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public double unitPrice { get; set; }
    
        public virtual SalesLocation SalesLocation { get; set; }
        public virtual Item Item { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
