//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncTransaction
    {
        public string tableName { get; set; }
        public string action { get; set; }
        public string value { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public System.Guid id { get; set; }
        public string branchID { get; set; }
    }
}
