//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimjaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.TelephoneFaxes = new HashSet<TelephoneFax>();
            this.UserLocations = new HashSet<UserLocation>();
        }
    
        public string userID { get; set; }
        public string fullName { get; set; }
        public string password { get; set; }
        public bool isActive { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<System.Guid> addressID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public int roleID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<TelephoneFax> TelephoneFaxes { get; set; }
        public virtual ICollection<UserLocation> UserLocations { get; set; }
        public virtual Role Roles { get; set; }
    }
}
